/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable.tracking.solution;

/**
 *
 * @author Bobo
 */
public class MainGUI extends javax.swing.JPanel {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listYearsP = new javax.swing.JPanel();
        year1BT = new javax.swing.JButton();
        year2BT = new javax.swing.JButton();
        year3BT = new javax.swing.JButton();
        year4BT = new javax.swing.JButton();
        classInfoP = new javax.swing.JPanel();
        tutorNLB = new javax.swing.JLabel();
        classNLB = new javax.swing.JLabel();
        nStudentsLB = new javax.swing.JLabel();
        adminFunctionsP = new javax.swing.JPanel();
        sStudentBT = new javax.swing.JButton();
        sStaffBT = new javax.swing.JButton();
        addStudentBT = new javax.swing.JButton();
        addStaffBT = new javax.swing.JButton();
        closeBT = new javax.swing.JButton();
        listStudentP = new javax.swing.JPanel();
        listStudentsLB = new javax.swing.JLabel();

        setName("Attendance Tracking Solutions"); // NOI18N
        setLayout(null);

        listYearsP.setBackground(new java.awt.Color(248, 148, 6));

        year1BT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        year1BT.setText("Year 1");

        year2BT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        year2BT.setText("Year 2");

        year3BT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        year3BT.setText("Year 3");

        year4BT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        year4BT.setText("Year 4");

        javax.swing.GroupLayout listYearsPLayout = new javax.swing.GroupLayout(listYearsP);
        listYearsP.setLayout(listYearsPLayout);
        listYearsPLayout.setHorizontalGroup(
            listYearsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listYearsPLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(year1BT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(year2BT)
                .addGap(18, 18, 18)
                .addComponent(year3BT)
                .addGap(18, 18, 18)
                .addComponent(year4BT)
                .addContainerGap(547, Short.MAX_VALUE))
        );
        listYearsPLayout.setVerticalGroup(
            listYearsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listYearsPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(listYearsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year1BT)
                    .addComponent(year2BT)
                    .addComponent(year3BT)
                    .addComponent(year4BT))
                .addGap(27, 27, 27))
        );

        add(listYearsP);
        listYearsP.setBounds(0, 0, 900, 50);

        classInfoP.setBackground(new java.awt.Color(248, 188, 8));

        tutorNLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tutorNLB.setText("Tutor name:");

        classNLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        classNLB.setText("Class name:");

        nStudentsLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nStudentsLB.setText("No.of Students:");

        javax.swing.GroupLayout classInfoPLayout = new javax.swing.GroupLayout(classInfoP);
        classInfoP.setLayout(classInfoPLayout);
        classInfoPLayout.setHorizontalGroup(
            classInfoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classInfoPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(classInfoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tutorNLB)
                    .addComponent(classNLB)
                    .addComponent(nStudentsLB))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        classInfoPLayout.setVerticalGroup(
            classInfoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classInfoPLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(tutorNLB)
                .addGap(28, 28, 28)
                .addComponent(classNLB)
                .addGap(31, 31, 31)
                .addComponent(nStudentsLB)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        add(classInfoP);
        classInfoP.setBounds(0, 50, 230, 410);

        adminFunctionsP.setBackground(new java.awt.Color(248, 148, 6));

        sStudentBT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sStudentBT.setText("Search Student");

        sStaffBT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sStaffBT.setText("Search Staff");

        addStudentBT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addStudentBT.setText("Add Student");

        addStaffBT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addStaffBT.setText("Add Staff");

        closeBT.setBackground(new java.awt.Color(192, 57, 43));
        closeBT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        closeBT.setText("Close");

        javax.swing.GroupLayout adminFunctionsPLayout = new javax.swing.GroupLayout(adminFunctionsP);
        adminFunctionsP.setLayout(adminFunctionsPLayout);
        adminFunctionsPLayout.setHorizontalGroup(
            adminFunctionsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminFunctionsPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sStudentBT)
                .addGap(18, 18, 18)
                .addComponent(sStaffBT)
                .addGap(18, 18, 18)
                .addComponent(addStudentBT)
                .addGap(18, 18, 18)
                .addComponent(addStaffBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                .addComponent(closeBT)
                .addContainerGap())
        );
        adminFunctionsPLayout.setVerticalGroup(
            adminFunctionsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminFunctionsPLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(adminFunctionsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sStudentBT)
                    .addComponent(sStaffBT)
                    .addComponent(addStudentBT)
                    .addComponent(addStaffBT)
                    .addComponent(closeBT))
                .addContainerGap())
        );

        add(adminFunctionsP);
        adminFunctionsP.setBounds(0, 460, 900, 50);

        listStudentP.setBackground(new java.awt.Color(44, 62, 80));
        listStudentP.setMinimumSize(new java.awt.Dimension(700, 440));

        listStudentsLB.setBackground(new java.awt.Color(255, 255, 255));
        listStudentsLB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        listStudentsLB.setForeground(new java.awt.Color(255, 255, 255));
        listStudentsLB.setText("List of Students");

        javax.swing.GroupLayout listStudentPLayout = new javax.swing.GroupLayout(listStudentP);
        listStudentP.setLayout(listStudentPLayout);
        listStudentPLayout.setHorizontalGroup(
            listStudentPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listStudentPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listStudentsLB)
                .addContainerGap(551, Short.MAX_VALUE))
        );
        listStudentPLayout.setVerticalGroup(
            listStudentPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listStudentPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listStudentsLB)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        add(listStudentP);
        listStudentP.setBounds(230, 50, 670, 410);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStaffBT;
    private javax.swing.JButton addStudentBT;
    private javax.swing.JPanel adminFunctionsP;
    private javax.swing.JPanel classInfoP;
    private javax.swing.JLabel classNLB;
    private javax.swing.JButton closeBT;
    private javax.swing.JPanel listStudentP;
    private javax.swing.JLabel listStudentsLB;
    private javax.swing.JPanel listYearsP;
    private javax.swing.JLabel nStudentsLB;
    private javax.swing.JButton sStaffBT;
    private javax.swing.JButton sStudentBT;
    private javax.swing.JLabel tutorNLB;
    private javax.swing.JButton year1BT;
    private javax.swing.JButton year2BT;
    private javax.swing.JButton year3BT;
    private javax.swing.JButton year4BT;
    // End of variables declaration//GEN-END:variables

    void pack() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void setDefaultCloseOperation(int EXIT_ON_CLOSE) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


}
